// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6_95ECYGNMOcYv5qR2V7HCOS3Hm97Bp4',
    appId: '1:934873230742:web:e9a13e261c771fc3c6c1b7',
    messagingSenderId: '934873230742',
    projectId: 'box-this',
    authDomain: 'box-this.firebaseapp.com',
    storageBucket: 'box-this.firebasestorage.app',
    measurementId: 'G-Q36FW7P4QY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC58coFdYFNAwBdYZl5H54fWT8msG25byc',
    appId: '1:934873230742:android:072aca908afef1e7c6c1b7',
    messagingSenderId: '934873230742',
    projectId: 'box-this',
    storageBucket: 'box-this.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIArHXH8oRDBDWeDAm5_94BJrZ5YQe10g',
    appId: '1:934873230742:ios:0cfda06549802365c6c1b7',
    messagingSenderId: '934873230742',
    projectId: 'box-this',
    storageBucket: 'box-this.firebasestorage.app',
    iosBundleId: 'com.example.boxThis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIArHXH8oRDBDWeDAm5_94BJrZ5YQe10g',
    appId: '1:934873230742:ios:0cfda06549802365c6c1b7',
    messagingSenderId: '934873230742',
    projectId: 'box-this',
    storageBucket: 'box-this.firebasestorage.app',
    iosBundleId: 'com.example.boxThis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6_95ECYGNMOcYv5qR2V7HCOS3Hm97Bp4',
    appId: '1:934873230742:web:36f275b18c966c62c6c1b7',
    messagingSenderId: '934873230742',
    projectId: 'box-this',
    authDomain: 'box-this.firebaseapp.com',
    storageBucket: 'box-this.firebasestorage.app',
    measurementId: 'G-8VDBWX656L',
  );
}
